services:
    cca.dc-general.backend_listener.create_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CreateHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.edit_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.copy_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
            - "@cca.dc-general.security-url-builder-factory"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.delete_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.paste_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.toggle_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\ToggleHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.list_view_show_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\ListViewShowAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
            - "@translator"
            - "@cca.translator.contao_translator"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.parent_list_view_show_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\ParentedListViewShowAllHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
            - "@translator"
            - "@cca.translator.contao_translator"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent

    cca.dc-general.backend_listener.select_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\SelectHandler
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            -   name: kernel.event_listener
                event: dc-general.action
                method: handleEvent
