services:
    cca.dc-general.backend_listener.backend_view_populator:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\BackendViewPopulator
        public: true
        arguments:
            - "@cca.dc-general.scope-matcher"
            - "@contao.csrf.token_manager"
            - "%contao.csrf_token_name%"
        tags:
            -   name: kernel.event_listener
                event: dc-general.factory.populate-environment
                method: process
                priority: 100
