services:
    cca.dc-general.backend_subsriber.subsriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_subscriber }

    cca.dc-general.backend_subsriber.clipboard_controller:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Controller\ClipboardController
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_subscriber }

    cca.dc-general.backend_subsriber.language_filter:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_subscriber }

    cca.dc-general.backend_subsriber.rich_text_file_uuid_subsriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\RichTextFileUuidSubscriber
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_subscriber }

    cca.dc-general.backend_subsriber.check_permission:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\CheckPermission
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_subscriber }

    cca.dc-general.backend_subsriber.dynmaic_parent_table:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\DynamicParentTableSubscriber
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_subscriber }
