services:
    cca.dc-general.backend_listener.extended_legacy_dca_populator:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\ExtendedLegacyDcaPopulator
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.factory.populate-environment, method: process, priority: 100 }

    cca.dc-general.backend_listener.backend_view_populator:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\BackendViewPopulator
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.factory.populate-environment, method: process, priority: 100 }

    cca.dc-general.backend_listener.picker_compat_populator:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\PickerCompatPopulator
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.factory.populate-environment, method: process, priority: -10000 }

    cca.dc-general.backend_listener.format_model_label_subscriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber
        calls:
            - method: setScopeDeterminator
              arguments:
                  - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.model.format_model_label, method: handleFormatModelLabel }

    cca.dc-general.backend_listener.get_group_header_subscriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\GetGroupHeaderSubscriber
        arguments:
            - "@event_dispatcher"
            - "@cca.translator.contao_translator"
        calls:
            - method: setScopeDeterminator
              arguments:
                  - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.view.contao2backend.get-group-header, method: handle }

    cca.dc-general.backend_listener.widget_builder:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder
        arguments:
            - "@cca.dc-general.environment"
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.view.contao2backend.build-widget, method: handleEvent }

    cca.dc-general.backend_listener.color_picker_wizard_subscriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\ColorPickerWizardSubscriber
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.view.contao2backend.build-widget, method: handleEvent }

    cca.dc-general.backend_listener.paste_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.create_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CreateHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.edit_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.select_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\SelectHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.copy_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.delete_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\DeleteHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.toggle_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\ToggleHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.list_view_show_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\ListViewShowAllHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.parent_list_view_show_all_handler:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\ParentedListViewShowAllHandler
        arguments:
            - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.action, method: handleEvent }

    cca.dc-general.backend_listener.backend_button_listener:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EventListener\BackButtonListener
        calls:
            - method: setScopeDeterminator
              arguments:
                  - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.view.contao2backend.get-global-button, method: handle }

    cca.dc-general.backend_listener.create_model_button_listener:
        class: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EventListener\CreateModelButtonListener
        calls:
            - method: setScopeDeterminator
              arguments:
                  - "@cca.dc-general.scope-matcher"
        tags:
            - { name: kernel.event_listener, event: dc-general.view.contao2backend.get-global-button, method: handle }
