services:
    cca.dc-general.general_subsriber.fallback_reset_subscriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber
        public: true
        tags:
            - { name: kernel.event_subscriber }
    cca.dc-general.general_subsriber.dynamic_parent_table_subscriber:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\DynamicParentTableSubscriber
        public: true
        tags:
            - { name: kernel.event_subscriber }
