services:
    cca.picker.tree_picker_provider:
        class: ContaoCommunityAlliance\DcGeneral\Contao\Picker\TreePickerProvider
        public: false
        arguments:
            - "@knp_menu.factory"
            - "@router"
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
        tags:
            - { name: contao.picker_provider }
